### ISSUE TITLE
Region is printed as unknown

### ISSUE THREAD

**Issue by sheldon-c73** [polarfire-soc/polarfire-soc-linux-examples#1]
**Device Name             Base Address    Size                    Size            Region
udmabuf-ddr-nc0         0xc0000000      0x08000000 bytes        128 MB          DDRC-NC1
udmabuf-ddr-c0          0xae000000      0x02000000 bytes        32 MB           DDRC-CACHE1
udmabuf-ddr-nc-wcb0     0xd8000000      0x08000000 bytes        128 MB          uknown**

This check on line 498
` ((base + sz) < (regions[i].base + regions[i].sz)))`
must be 
` ((base + sz) <= (regions[i].base + regions[i].sz)))` so that it prints **DDRC-NC-WCB1**

also the typo needs to be corrected to unknown.

**Comment by mcnamarad1971** [comment]
We'll certainly look at that and tidy it up

**Comment by mcnamarad1971** [comment]
That's fixed and should propagate through our release process.

**Comment by Cyril-Jean** [comment]
@sheldon-c73 Can you please close this issue if you are satisfied it is resolved?

**Comment by sheldon-c73** [comment]
Its fixed now.
