### ISSUE TITLE
[iio-http-server/app/views.py::makereadings] opposite VDD label ordering  (VDD, VDDA,25, VDD25, VDDA)

### ISSUE THREAD

**Issue by okawaj9** [polarfire-soc/polarfire-soc-linux-examples#2]
Current implementation of "views.py" is below.  But schematic, linux driver and pac1934 register map index ordering is opposite.  It was confirmed by reviewing linux driver code, schematic, pac1934 register map and ICICLE-KIT hardware design update and device tree update to see VDDA current consumption (removing PCIe/XCVR hardware component and PCIe statement from device tree) because VDDA is for XCVR.

* Current implementation of "views.py":  Index 0:VDDA, 1:VDD25, 2:VDDA25, 3:VDD
* Correct: Index 0:VDD, 1:VDDA25, 2:VDD25, 3:VDDA

(Current implementation)
def makereadings(current, currenthistory, voltage, voltagehistory):
    readings = [
        {
            "channel": "VDDA",
            "index": 0,
        },
        {
            "channel": "VDD25",
            "index": 1,
        },
        {
            "channel": "VDDA25",
            "index": 2,
        },
        {
            "channel": "VDD",
            "index": 3,
        }
    ]

<img width="1004" alt="image001" src="https://user-images.githubusercontent.com/61904969/129739370-7235f5e8-cd26-4468-9d80-6b7ed6f1a802.png">

![bbb](https://user-images.githubusercontent.com/61904969/129739881-9f290942-ae4e-4a96-a1d4-d299caf55eef.png)

<img width="822" alt="スクリーンショット 2021-08-17 23 03 07" src="https://user-images.githubusercontent.com/61904969/129740225-641b431f-4647-4390-b516-6a2abc3e3ef6.png">

Best Regards,

**Comment by Cyril-Jean** [comment]
Agreed. Fix on its way.

**Comment by Cyril-Jean** [comment]
The fix for this issue is available on the main/master branch.

**Comment by okawaj9** [comment]
Thx
